	/*AVALILABLE AMDIN THEMES ACTIONS*/
export const DARK_THEME = "DARK_THEME";
export const LIGHT_THEME = "LIGHT_THEME";
export const NO_THEME = "NO_THEME";
	/*AVALILABLE AMDIN STORE ACTIONS*/
export const SET_AUTH_USER = "SET_AUTH_USER";
export const NOTHING_TO_SET = "NOTHING_TO_SET";